name: ss-notebooks
channels:
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cycler=0.10.0
  - freetype=2.10.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - intel-openmp=2019.3
  - jpeg=9c
  - kiwisolver=1.1.0
  - libblas=3.8.0
  - libcblas=3.8.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mkl=2019.3
  - numpy=1.16.3
  - openssl=1.1.1b
  - pandas=0.24.2
  - pip=19.1
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyreadline=2.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - qt=5.9.7
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.26.0
  - tornado=6.0.2
  - vc=14.1
  - vs2015_runtime=14.15.26706
  - wheel=0.33.1
  - wincertstore=0.2
  - zlib=1.2.11
